---

 caption:   "Resultados obtenidos en las pruebas realizadas con las distintas consideraciones del espacio desconocido al construir el GVD."
 label:     "tab:desconocido3"

 mode:      "celda"
 test_type: "desconocido"

 float_format:
   default:
     mean_f:   "f"
     mean_d:   "6"
     stddev_f: "e"
     stddev_d: "1"

 data_dirs:
   - "cell_size/inc_fsm5_gcm1"
   - "cell_size/inc_fsm5_gcm2"

 metrics:
   - "map_completeness" 
   - "map_quality"
