---

 caption:   "Resultados obtenidos en las pruebas realizadas con las distintas consideraciones del espacio desconocido al construir el GVD."
 label:     "tab:desconocido1"

 float_format:
   default:
     mean_f:   "f"
     mean_d:   "1"
     stddev_f: "f"
     stddev_d: "1"
   gvd_construction_time_mean:
     mean_f:   "f"
     mean_d:   "4"
     stddev_f: "f"
     stddev_d: "4"

 mode:      "celda"
 test_type: "desconocido"

 data_dirs:
   - "cell_size/inc_fsm5_gcm1"
   - "cell_size/inc_fsm5_gcm2"

 metrics:
   - "exploration_time"
   - "exploration_cost"
   - "gvd_construction_time_mean"
