---

 caption:   "Resultados de tiempo y costo de exploración obtenidos en las pruebas realizadas con los distintos métodos de identificación de objetivos."
 label:     "tab:ident_obj1"

 float_format:
   default:
     mean_f:   "f"
     mean_d:   "1"
     stddev_f: "f"
     stddev_d: "1"
   obj_id_time_mean:
     mean_f:   "f"
     mean_d:   "4"
     stddev_f: "f"
     stddev_d: "4"

 mode:      "celda"
 test_type: "ident_obj"

 data_dirs:
   - "cell_size/inc_fsm5_gcm1"
   - "cell_size/inc_fsm2_gcm1"
   - "cell_size/inc_fsm0_gcm1"

 metrics:
   - "exploration_time" 
   - "exploration_cost" 
   - "obj_id_time_mean" 

