---

 caption:   "Resultados de completitud y calidad de los mapas obtenidos en las pruebas realizadas con los distintos métodos de identificación de objetivos."
 label:     "tab:ident_obj3"

 mode:      "celda"
 test_type: "ident_obj"

 float_format:
   default:
     mean_f:   "f"
     mean_d:   "6"
     stddev_f: "e"
     stddev_d: "1"

 data_dirs:
   - "cell_size/inc_fsm5_gcm1"
   - "cell_size/inc_fsm2_gcm1"
   - "cell_size/inc_fsm0_gcm1"

 metrics:
   - "map_completeness" 
   - "map_quality"
