---

 caption:   "Resultados relacionados a los tiempos de construcción del GVD obtenidos en las pruebas realizadas con la construcción incremental y no incremental del GVD."
 label:     "tab:inc2"

 mean_float_format:   "f"
 mean_float_decimals: "2"

 stddev_float_format:   "f"
 stddev_float_decimals: "3"

 mode:      "celda"
 test_type: "incrementalidad"

 data_dirs:
   - "cell_size/inc_fsm5_gcm1"
   - "cell_size/noninc_fsm5_gcm1"

 metrics:
   # - "exploration_time" 
   # - "exploration_cost" 
   # - "erroneous_area" 

   # - "explored_area" 
   # - "exploration_efficiency"
   # - "map_completeness" 
   # # - "map_quality"

   # - "auction_info_time_diff_max" 
   # - "auction_info_time_diff_mean" 
   # - "auction_info_time_diff_min"
   # - "auction_info_time_diff_sum" 
   # - "auction_info_time_max"
   # - "auction_info_time_mean" 
   # - "auction_info_time_min"
   # - "auction_info_time_sum" 

   # - "gvd_construction_time_diff_max" 
   # - "gvd_construction_time_diff_mean" 
   # - "gvd_construction_time_diff_min"
   # - "gvd_construction_time_diff_sum" 
   # - "gvd_construction_time_max"    
   # - "gvd_construction_time_mean" 
   # - "gvd_construction_time_min" 
   - "gvd_construction_time_sum" 

   - "gvd_update_auction_info_percent" 
   # - "gvd_update_auction_info_percent_log_max" 
   # - "gvd_update_auction_info_percent_log_mean" 
   # - "gvd_update_auction_info_percent_log_min"
   # - "gvd_update_auction_info_percent_log_sum" 
