---

 caption:   "Resultados de completitud y calidad de los mapas obtenidos en las pruebas realizadas con la construcción incremental y no incremental del GVD."
 label:     "tab:inc3"

 mode:      "celda"
 test_type: "incrementalidad"

 float_format:
   default:
     mean_f:   "f"
     mean_d:   "6"
     stddev_f: "e"
     stddev_d: "1"

 data_dirs:
   - "cell_size/inc_fsm5_gcm1"
   - "cell_size/noninc_fsm5_gcm1"

 metrics:
   - "map_completeness" 
   - "map_quality"
